### ISSUE TITLE
Files missing in repository

### ISSUE THREAD

**Issue by BlackMac** [corebonts/hass-cudy-router#4]
There are files being loaded that are missing from this repository:

```
Logger: homeassistant.helpers.integration_platform
Source: loader.py:850
First occurred: 9:25:04 PM (5 occurrences)
Last logged: 9:25:04 PM

Unexpected error importing cudy_router/diagnostics.py
Unexpected error importing cudy_router/recorder.py
Unexpected error importing cudy_router/media_source.py
Unexpected error importing cudy_router/logbook.py
Unexpected error importing cudy_router/system_health.py
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/integration_platform.py", line 50, in _async_process_single_integration_platform_component
    platform = integration.get_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 833, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 850, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'custom_components.cudy-router.diagnostics'

```

**Comment by corebonts** [comment]
That might be some copypaste error of mine. Thanks, I will have a look.

**Comment by corebonts** [comment]
I learned that the folder name should be exactly the integration's domain name, which is `cudy_router`. Please rename your folder under `custom_components` which is `cudy-router` as I see, with a dash instead of an underscore.
